# Generated by Django 4.2.4 on 2023-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinksCryptoInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crypto_id', models.IntegerField(unique=True)),
                ('crypto_name', models.CharField(max_length=40)),
                ('abbr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'links_crypto_info',
                'indexes': [models.Index(fields=['id'], name='links_crypt_id_0d0cf7_idx')],
            },
        ),
    ]
