# Generated by Django 4.2.4 on 2023-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinksExchangeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_id', models.IntegerField(unique=True)),
                ('exchange_name', models.CharField(max_length=40)),
                ('info_reverse', models.FloatField(default=0)),
                ('info_age', models.CharField(default='Zero', max_length=40)),
                ('info_star', models.IntegerField(default=0)),
                ('info_verification', models.BooleanField(default=False)),
                ('info_registration', models.BooleanField(default=False)),
                ('addition_floating', models.BooleanField(default=False)),
                ('addition_verifying', models.BooleanField(default=False)),
                ('addition_manual', models.BooleanField(default=False)),
                ('addition_percent', models.BooleanField(default=False)),
                ('addition_otherin', models.BooleanField(default=False)),
                ('addition_reg', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'links_exchange_info',
                'indexes': [models.Index(fields=['id'], name='links_excha_id_a3237a_idx')],
            },
        ),
    ]
